apiVersion: v1
kind: Service
metadata:
  name: my-laraiptv-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-laraiptv
  labels:
    app: laraiptv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laraiptv
  template:
    metadata:
      labels:
        app: laraiptv
    spec:
      containers:
      - name: laraiptv
        image: 10.9.38.104:5000\lar-ipt_v2
        ports:
        - containerPort: 80
